/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CareRouteImport } from './routes/care'
import { Route as FireRouteImport } from './routes/fire'
import { Route as PlantRouteImport } from './routes/plant'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedModerateRouteImport } from './routes/_authenticated/moderate'
import { Route as MyTokenRouteImport } from './routes/my/$token'
import { Route as ApiMobileSubmissionsRouteImport } from './routes/api/mobile/submissions'
import { Route as ApiPublicHotspotsRouteImport } from './routes/api/public/hotspots'
import { Route as ApiPublicPhotoSplatRouteImport } from './routes/api/public/photo/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CareRoute = CareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => rootRouteImport,
} as any)
const FireRoute = FireRouteImport.update({
  id: '/fire',
  path: '/fire',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantRoute = PlantRouteImport.update({
  id: '/plant',
  path: '/plant',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModerateRoute = AuthenticatedModerateRouteImport.update({
  id: '/moderate',
  path: '/moderate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const MyTokenRoute = MyTokenRouteImport.update({
  id: '/my/$token',
  path: '/my/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileSubmissionsRoute = ApiMobileSubmissionsRouteImport.update({
  id: '/api/mobile/submissions',
  path: '/api/mobile/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHotspotsRoute = ApiPublicHotspotsRouteImport.update({
  id: '/api/public/hotspots',
  path: '/api/public/hotspots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPhotoSplatRoute = ApiPublicPhotoSplatRouteImport.update({
  id: '/api/public/photo/$',
  path: '/api/public/photo/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/care': typeof CareRoute
  '/fire': typeof FireRoute
  '/plant': typeof PlantRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/volunteer': typeof VolunteerRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/moderate': typeof AuthenticatedModerateRoute
  '/my/$token': typeof MyTokenRoute
  '/api/mobile/submissions': typeof ApiMobileSubmissionsRoute
  '/api/public/hotspots': typeof ApiPublicHotspotsRoute
  '/api/public/photo/$': typeof ApiPublicPhotoSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/care': typeof CareRoute
  '/fire': typeof FireRoute
  '/plant': typeof PlantRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/volunteer': typeof VolunteerRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/moderate': typeof AuthenticatedModerateRoute
  '/my/$token': typeof MyTokenRoute
  '/api/mobile/submissions': typeof ApiMobileSubmissionsRoute
  '/api/public/hotspots': typeof ApiPublicHotspotsRoute
  '/api/public/photo/$': typeof ApiPublicPhotoSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/care': typeof CareRoute
  '/fire': typeof FireRoute
  '/plant': typeof PlantRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/volunteer': typeof VolunteerRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/moderate': typeof AuthenticatedModerateRoute
  '/my/$token': typeof MyTokenRoute
  '/api/mobile/submissions': typeof ApiMobileSubmissionsRoute
  '/api/public/hotspots': typeof ApiPublicHotspotsRoute
  '/api/public/photo/$': typeof ApiPublicPhotoSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/care'
    | '/fire'
    | '/plant'
    | '/privacy'
    | '/terms'
    | '/volunteer'
    | '/activity'
    | '/admin'
    | '/moderate'
    | '/my/$token'
    | '/api/mobile/submissions'
    | '/api/public/hotspots'
    | '/api/public/photo/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/care'
    | '/fire'
    | '/plant'
    | '/privacy'
    | '/terms'
    | '/volunteer'
    | '/activity'
    | '/admin'
    | '/moderate'
    | '/my/$token'
    | '/api/mobile/submissions'
    | '/api/public/hotspots'
    | '/api/public/photo/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/care'
    | '/fire'
    | '/plant'
    | '/privacy'
    | '/terms'
    | '/volunteer'
    | '/_authenticated/activity'
    | '/_authenticated/admin'
    | '/_authenticated/moderate'
    | '/my/$token'
    | '/api/mobile/submissions'
    | '/api/public/hotspots'
    | '/api/public/photo/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CareRoute: typeof CareRoute
  FireRoute: typeof FireRoute
  PlantRoute: typeof PlantRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  VolunteerRoute: typeof VolunteerRoute
  MyTokenRoute: typeof MyTokenRoute
  ApiMobileSubmissionsRoute: typeof ApiMobileSubmissionsRoute
  ApiPublicHotspotsRoute: typeof ApiPublicHotspotsRoute
  ApiPublicPhotoSplatRoute: typeof ApiPublicPhotoSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care': {
      id: '/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof CareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fire': {
      id: '/fire'
      path: '/fire'
      fullPath: '/fire'
      preLoaderRoute: typeof FireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plant': {
      id: '/plant'
      path: '/plant'
      fullPath: '/plant'
      preLoaderRoute: typeof PlantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/moderate': {
      id: '/_authenticated/moderate'
      path: '/moderate'
      fullPath: '/moderate'
      preLoaderRoute: typeof AuthenticatedModerateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/my/$token': {
      id: '/my/$token'
      path: '/my/$token'
      fullPath: '/my/$token'
      preLoaderRoute: typeof MyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/submissions': {
      id: '/api/mobile/submissions'
      path: '/api/mobile/submissions'
      fullPath: '/api/mobile/submissions'
      preLoaderRoute: typeof ApiMobileSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hotspots': {
      id: '/api/public/hotspots'
      path: '/api/public/hotspots'
      fullPath: '/api/public/hotspots'
      preLoaderRoute: typeof ApiPublicHotspotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/photo/$': {
      id: '/api/public/photo/$'
      path: '/api/public/photo/$'
      fullPath: '/api/public/photo/$'
      preLoaderRoute: typeof ApiPublicPhotoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedModerateRoute: typeof AuthenticatedModerateRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedModerateRoute: AuthenticatedModerateRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CareRoute: CareRoute,
  FireRoute: FireRoute,
  PlantRoute: PlantRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  VolunteerRoute: VolunteerRoute,
  MyTokenRoute: MyTokenRoute,
  ApiMobileSubmissionsRoute: ApiMobileSubmissionsRoute,
  ApiPublicHotspotsRoute: ApiPublicHotspotsRoute,
  ApiPublicPhotoSplatRoute: ApiPublicPhotoSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
